spring:
  datasource:
    url: jdbc:mysql://localhost:3306/starbucks_database
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

JWT:
  secret-key: 52f47oq9Tvm5nrsXEIJCnfEfmVyRLnyzKeJiEN5fld4=
  token:
    access-expire-time: 60000